language: "en" # The language to use for the plugin
playerData:
  enabled: true # Whether to save player data to the database
  saveName: false # Whether to save the player's name to the database.
oauth:
  webPort: 8080 # The port to run the web server on
  client_id: "YOUR_CLIENT_ID" # The client ID provided by Microsoft
  client_secret: "YOUR_CLIENT_SECRET" # The client secret provided by Microsoft
  redirect_uri: "http://yourserver.com/auth" # The URI to redirect to after authentication (must match the URI configured with Microsoft)
  organization_domain: "example.com" # The domain of the organization to verify against