name: HTL_auth
version: '${project.version}'
main: xyz.thetwoboom.htl_auth.HTL_auth
description: 'Easy Authentication for Minecraft via Microsoft Entra ID'
author: TheTwoBoom
depend: [LuckPerms]
website: 'https://github.com/TheTwoBoom/HTL_auth'
api-version: '1.21.8'
commands:
  verify:
    description: "Verify your account"
    usage: "/verify"
  lookup:
    description: "Shows information about a player"
    usage: "/lookup <player>"
    permission: "htlauth.lookup"
  htlauth:
    description: "Main command for HTL_auth"
    usage: "/htlauth <reload/help/forceverify/reverify>"
    permission: "htlauth.admin"
folia-supported: true